const CONTENT = {
    u1: {
        grammar: [
            { question: "He _____ his car every weekend.", options: ["A) wash", "B) washes", "C) washing", "D) washed"], correct: "B" },
            { question: "_____ she _____ French?", options: ["A) Do / speaks", "B) Does / speaks", "C) Does / speak", "D) Is / speak"], correct: "C" },
            { question: "We _____ tennis on Monday evenings, but my little sister _____ on Sundays.", options: ["A) play / play", "B) plays / plays", "C) play / plays", "D) plays / play"], correct: "C" },
            { question: "Where _____ you now?", options: ["A) were", "B) do", "C) are", "D) is"], correct: "C" },
            { question: "He _____ some new shoes last month.", options: ["A) bought", "B) buying", "C) buy", "D) buys"], correct: "A" },
            { question: "Where _____ you _____ on holiday last year?", options: ["A) did / went", "B) go / did", "C) did / go", "D) do / go"], correct: "C" },
            { question: "What month _____ it last month?", options: ["A) was", "B) is", "C) were", "D) did"], correct: "A" },
            { question: "A: _____ Lama _____ you yesterday evening? B: No, she _____.", options: ["A) Did / helped / didn’t", "B) Did / helped / did", "C) Did / help / did", "D) Did / help / didn’t"], correct: "D" },
            { question: "He _____ the school in 1994.", options: ["A) left", "B) leaved", "C) leave", "D) leaves"], correct: "A" },
            { question: "I _____ to the U.S.A. ten years ago.", options: ["A) went", "B) go", "C) visit", "D) gone"], correct: "A" },
            { question: "I am _____ tennis this afternoon.", options: ["A) play", "B) playing", "C) to play", "D) played"], correct: "B" },
            { question: "I’m not _____ to buy you lunch, today.", options: ["A) go", "B) going", "C) goes", "D) to go"], correct: "B" },
            { question: "She _____ traveled to most parts of the world.", options: ["A) have", "B) is", "C) has", "D) will"], correct: "C" },
            { question: "Have you _____ your homework?", options: ["A) do", "B) to do", "C) done", "D) did"], correct: "C" },
            { question: "She has _____ to Portugal.", options: ["A) going", "B) went", "C) gone", "D) went"], correct: "C" },
            { question: "She has _____ to Portugal.", options: ["A) be", "B) been", "C) being", "D) were"], correct: "B" },
            { question: "_____ they go to Australia last month?", options: ["A) Have", "B) Do", "C) Has", "D) Did"], correct: "D" },
            { question: "She has _____ the letter. She _____ it yesterday.", options: ["A) wrote / wrote", "B) written / written", "C) wrote / written", "D) written / wrote"], correct: "D" },
            { question: "I’ve _____ my homework. I _____ it after supper.", options: ["A) done / done", "B) did / done", "C) done / did", "D) did / did"], correct: "C" },
            { question: "I __________ TV when the phone __________.", options: ["A) watched / was ringing", "B) was watching / rang", "C) was watching / was ringing", "D) watched / rang"], correct: "B" },
            { question: "They __________ football when it suddenly __________ to rain.", options: ["A) played / started", "B) were playing / started", "C) were playing / starting", "D) played / starting"], correct: "B" }
        ]

    },
    u2: {
        grammar: [
            { question: "She ___ reading for two hours.", options: ["A) has been", "B) have been", "C) is", "D) was"], correct: "A" },
            { question: "How long ___ you ___ playing football?", options: ["A) have / been", "B) has / been", "C) do / been", "D) did / been"], correct: "A" },
            { question: "He ___ for three different teams.", options: ["A) has played", "B) have played", "C) has been playing", "D) played"], correct: "A" },
            { question: "She ___ 20 pages so far.", options: ["A) have read", "B) has read", "C) has been reading", "D) read"], correct: "B" },
            { question: "Ahmed ___ in a hospital.", options: ["A) work", "B) works", "C) working", "D) worked"], correct: "B" },
            { question: "They ___ football on weekends.", options: ["A) don’t play", "B) doesn’t play", "C) not play", "D) plays"], correct: "A" },
            { question: "She ___ to school every day.", options: ["A) go", "B) goes", "C) going", "D) gone"], correct: "B" },
            { question: "He works at the hospital ___ Sunday to Thursday.", options: ["A) on", "B) in", "C) from", "D) at"], correct: "C" },
            { question: "He doesn’t work ___ the weekend.", options: ["A) in", "B) at", "C) on", "D) from"], correct: "B" },
            { question: "_____ summer I play tennis _____ Sundays.", options: ["A) In / in", "B) At / on", "C) In / on", "D) At / in"], correct: "C" },
            { question: "I usually study ___ the evening.", options: ["A) at", "B) on", "C) in", "D) from"], correct: "A" },
            { question: "We don’t work ___ weekdays.", options: ["A) in", "B) on", "C) at", "D) from"], correct: "B" },
            { question: "___ does he work? – He works in a hospital.", options: ["A) Where", "B) What", "C) Who", "D) When"], correct: "A" },
            { question: "___ do you do? – I’m a doctor.", options: ["A) Where", "B) What", "C) Who", "D) How"], correct: "B" },
            { question: "The man ___ is standing over there is my uncle.", options: ["A) which", "B) that", "C) who", "D) whom"], correct: "C" },
            { question: "This is the computer ___ I use for work.", options: ["A) which", "B) who", "C) where", "D) when"], correct: "A" },
            { question: "I was studying while my friend ___ TV.", options: ["A) watched", "B) were watching", "C) was watching", "D) watches"], correct: "C" },
            { question: "While she ___ her homework, her brother was playing computer games.", options: ["A) does", "B) was doing", "C) did", "D) is doing"], correct: "B" }
        ]
    },
    u3: {
        grammar: [
            { question: "I forgot my wallet! — Don’t worry, I _______ pay for you.", options: ["A) am going to", "B) will", "C) am paying", "D) was"], correct: "B" },
            { question: "Maybe I _______ go to Abha next month.", options: ["A) am going to", "B) will", "C) am going", "D) was"], correct: "B" },
            { question: "I think people _______ live on Mars one day.", options: ["A) are going to", "B) will", "C) are living", "D) do"], correct: "B" },
            { question: "You dropped your books! I _______ help you.", options: ["A) am going to", "B) will", "C) was", "D) am helping"], correct: "B" },
            { question: "I _______ visit my grandparents this weekend. I already told them I’d come.", options: ["A) will", "B) am going to", "C) might", "D) was"], correct: "B" },
            { question: "She _______ study medicine after high school.", options: ["A) will", "B) is going to", "C) studies", "D) might"], correct: "B" },
            { question: "Watch out! You _______ drop your phone!", options: ["A) will", "B) are going to", "C) can", "D) dropped"], correct: "B" },
            { question: "This time tomorrow, I _______ in the ocean.", options: ["A) swim", "B) will be swimming", "C) am swimming", "D) going to swim"], correct: "B" },
            { question: "A week from today, I _______ on the beach.", options: ["A) will be relaxing", "B) am relaxing", "C) going to relax", "D) relax"], correct: "A" },
            { question: "By the year 3000, people _______ to the age of 120.", options: ["A) live", "B) are living", "C) will be living", "D) will live"], correct: "C" },
            { question: "He _______ to Dubai tonight.", options: ["A) fly", "B) is flying", "C) flies", "D) going to fly"], correct: "B" },
            { question: "They _______ out next year.", options: ["A) are coming", "B) come", "C) will coming", "D) comes"], correct: "A" },
            { question: "What are you going to do in the summer?", options: ["A) I’ll probably travel.", "B) I’m going now.", "C) I travel every day.", "D) I’m traveling yesterday."], correct: "A" },
            { question: "Where will you go?", options: ["A) I go to Najran.", "B) I’m going to Najran.", "C) I’ll go to Najran.", "D) I went to Najran."], correct: "C" },
            { question: "How will you get there?", options: ["A) Maybe I’ll drive.", "B) I’m driving now.", "C) I drive always.", "D) I drove before."], correct: "A" },
            { question: "Global warming will melt the ice at the poles, _______?", options: ["A) will it", "B) won’t it", "C) isn’t it", "D) doesn’t it"], correct: "B" },
            { question: "People won’t live on other planets in 100 years, _______?", options: ["A) will they", "B) won’t they", "C) do they", "D) aren’t they"], correct: "A" },
            { question: "Scientists are close to finding a cure for cancer, _______?", options: ["A) are they", "B) aren’t they", "C) did they", "D) don’t they"], correct: "B" },
            { question: "It doesn’t usually rain in summer, _______?", options: ["A) does it", "B) is it", "C) isn’t it", "D) did it"], correct: "A" },
            { question: "Let’s look for the hidden treasure.", options: ["A) We can’t. We don’t have a map.", "B) No, I didn’t.", "C) Yes, I did.", "D) I’m going."], correct: "A" },
            { question: "Why don’t we make a capsule for the school project?", options: ["A) That sounds great!", "B) I can’t go.", "C) We won’t.", "D) I’m busy."], correct: "A" },
            { question: "How about visiting the museum tomorrow?", options: ["A) Great idea!", "B) I don’t.", "C) I can’t.", "D) Maybe later."], correct: "A" }
        ],
        vocabulary: [
            { question: "I need a new _____ to make toast in the morning.", options: ["A) whale", "B) rocket", "C) appliance", "D) tentacle"], correct: "C" },
            { question: "Can you _____ this file to your email?", options: ["A) dive", "B) attach", "C) optimize", "D) activate"], correct: "B" },
            { question: "\"No kidding?\" is used when you feel _____.", options: ["A) angry", "B) surprised", "C) bored", "D) tired"], correct: "B" },
            { question: "The _____ cleaned the floor and washed the dishes automatically.", options: ["A) rocket", "B) robot", "C) character", "D) submarine"], correct: "B" },
            { question: "The _____ traveled into space to study the moon.", options: ["A) novel", "B) rocket", "C) submarine", "D) appliance"], correct: "B" },
            { question: "The city built a new _____ with 80 floors.", options: ["A) skyscraper", "B) whale", "C) shipwreck", "D) prediction"], correct: "A" },
            { question: "You should _____ your progress to make sure you are improving.", options: ["A) monitor", "B) dive", "C) attach", "D) explore"], correct: "A" },
            { question: "obsolete", options: ["A) complete", "B) outdated", "C) high-tech", "D) expensive"], correct: "B" },
            { question: "He said “_____” to agree politely with his teacher.", options: ["A) Certainly", "B) Maybe", "C) No kidding", "D) Visionary"], correct: "A" },
            { question: "Scientists made a _____ about the weather for next week.", options: ["A) prediction", "B) robot", "C) shard", "D) haircut"], correct: "A" },
            { question: "The car is _____; it doesn’t use electricity.", options: ["A) gas-powered", "B) high-speed", "C) integral", "D) preventive"], correct: "A" },
            { question: "Engineers try to _____ systems to make them work faster.", options: ["A) dive", "B) optimize", "C) attach", "D) monitor"], correct: "B" },
            { question: "The company used strong _____ to build the bridge.", options: ["A) glass", "B) novel", "C) steel", "D) range"], correct: "C" },
            { question: "The _____ wrote a book about future technology.", options: ["A) whale", "B) visionary", "C) shipwreck", "D) explorer"], correct: "B" },
            { question: "to gather", options: ["A) to come together", "B) to separate", "C) to run", "D) to cook"], correct: "A" },
            { question: "to witness", options: ["A) to give evidence", "B) to help", "C) to see an event", "D) to read"], correct: "C" },
        ]
    }
};